### ISSUE TITLE
Feedback or Improvement suggestions

### ISSUE THREAD

**Issue by ProgramKingAbel** [ProgramKingAbel/Abel-Morara-Portfolio#4]
The team appreciated the work and effort made towards the project. 
Design was well-done
Improvements suggested on the responsiveness of the desktop version i.e overlap of a few elements i.e through effective use of the CSS grid.

**Comment by misikira** [comment]
good work

**Comment by axcell-0** [comment]
great job bro excellent

**Comment by omer-creator** [comment]
Good Work
